/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_packpublishing_asynchronousandroid_chapter9_GrayImageLoader */

#ifndef _Included_com_packpublishing_asynchronousandroid_chapter9_GrayImageLoader
#define _Included_com_packpublishing_asynchronousandroid_chapter9_GrayImageLoader
#ifdef __cplusplus
extern "C" {
#endif
#undef com_packpublishing_asynchronousandroid_chapter9_GrayImageLoader_DEBUG
#define com_packpublishing_asynchronousandroid_chapter9_GrayImageLoader_DEBUG 0L
/*
 * Class:     com_packpublishing_asynchronousandroid_chapter9_GrayImageLoader
 * Method:    convertImageToGray
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_packpublishing_asynchronousandroid_chapter9_GrayImageLoader_convertImageToGray
        (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
