/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_packpublishing_asynchronousandroid_chapter9_CPUStat */

#ifndef _Included_com_packpublishing_asynchronousandroid_chapter9_CPUStat
#define _Included_com_packpublishing_asynchronousandroid_chapter9_CPUStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_packpublishing_asynchronousandroid_chapter9_CPUStat
 * Method:    getRSSMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_packpublishing_asynchronousandroid_chapter9_JCPUStat_getRSSMemory
        (JNIEnv *, jobject);

/*
 * Class:     com_packpublishing_asynchronousandroid_chapter9_CPUStat
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_packpublishing_asynchronousandroid_chapter9_JCPUStat_dispose
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
